version: '3.8'

services:
  square-node:
    build:
      context: ./square_node
    container_name: square-node-container
    ports:
      - "5050:5000"

  cube-node:
    build:
      context: ./cube_node
    container_name: cube-node-container
    ports:
      - "5001:5001"
  demand-forecaster:
    build:
      context: ./demand_forecaster
    container_name: demand-forecaster-container
    ports:
      - "5002:5002"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  load-optimizer:
    build:
      context: ./load_optimizer
    container_name: load-optimizer-container
    ports:
      - "5003:5003"
  data-ingestor:
    build:
      context: ./data_ingestor
    container_name: data-ingestor-container
    ports:
      - "5004:5004"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  data-preprocessor:
    build:
      context: ./data_preprocessor
    container_name: data-preprocessor-container
    ports:
      - "5005:5005"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  anomaly-detector:
    build:
      context: ./anomaly_detector
    container_name: anomaly-detector-container
    ports:
      - "5006:5006"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  alert-node:
    build:
      context: ./data_alert_node
    container_name: alert-node-container
    ports:
      - "5007:5007"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  data-rebalancer:
    build:
      context: ./grid_rebalancer_node
    container_name: data-rebalancer-container
    ports:
      - "5008:5008"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  storage-optimizer:
    build:
      context: ./storage_optimizer_node
    container_name: storage-optimizer-container
    ports:
      - "5009:5009"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  ml-preprocessor:
    build:
      context: ./ml_preprocessor_node
    container_name: ml-preprocessor-container
    ports:
      - "5010:5010"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  ml-forecaster:
    build:
      context: ./ml_forecaster_node
    container_name: ml-forecaster-container
    ports:
      - "5011:5011"
    volumes:
      - ./data_ingestor/EirGrid_Data_Download/Downloaded_Data:/app/Downloaded_Data
  context-service:
    build:
      context: ./context_service_node
    container_name: context-service-container
    ports:
      - "5012:5012"
  smart-agent:
    build:
      context: ./smart_agent_node
    container_name: smart-agent-container
    ports:
      - "5013:5013"
  registry-node:
    build:
      context: ./registry_node
    container_name: registry-node-container
    ports:
      - "5014:5014"